services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    volumes:
      # Bind mount current directory (code) into the container's /app
      - ./:/app
      # This ensures the container uses its own node_modules created by npm install
      - /app/node_modules
    env_file:
      - .env
