import { PermissionKeys } from "@/constants/permissions";
import {
  BookA,
  BookmarkCheck,
  BookOpenCheck,
  BriefcaseBusiness,
  CalendarClock,
  ListTodo,
  LucideGraduationCap,
  Megaphone,
  Newspaper,
  Table,
  UserRound,
  Users,
  Warehouse,
  ChartNoAxesColumnIncreasing,
  NotebookPen,
} from "lucide-react";

export const navLinks = [
  {
    id: "branches",
    title: "الفروع",
    icon: Warehouse,
    url: "/itkan-dashboard/branches",
    permissions: [PermissionKeys.SYSTEM_BRANCHES_VIEW],
  },
  {
    id: "roles",
    title: "الادوار الوظيفية",
    icon: BookA,
    url: "/itkan-dashboard/roles",
    permissions: [PermissionKeys.SYSTEM_ROLES_VIEW],
  },
  {
    id: "staff",
    title: "المديرين",
    icon: BriefcaseBusiness,
    url: "/itkan-dashboard/staff",
    permissions: [PermissionKeys.SYSTEM_STAFF_VIEW],
  },
  {
    id: "students",
    title: "الطلاب",
    icon: LucideGraduationCap,
    url: "/itkan-dashboard/students",
    permissions: [PermissionKeys.SYSTEM_STUDENTS_VIEW],
  },
  {
    id: "parents",
    title: "أولياء الأمور",
    icon: Users,
    url: "/itkan-dashboard/parents",
    permissions: [PermissionKeys.SYSTEM_PARENTS_VIEW],
  },
  {
    id: "classes",
    title: "الفصول",
    icon: BookmarkCheck,
    url: "/itkan-dashboard/classes",
    permissions: [PermissionKeys.SYSTEM_TEACHERS_VIEW],
  },
  {
    id: "teachers",
    title: "المعلمين",
    icon: UserRound,
    url: "/itkan-dashboard/teachers",
    permissions: [PermissionKeys.SYSTEM_TEACHERS_VIEW],
  },
  {
    id: "attendance_and_evaluations",
    title: "الحضور و التقييمات",
    icon: BookmarkCheck,
    url: "/itkan-dashboard/attendance-and-evaluations",
    permissions: [PermissionKeys.EVALUATION_STUDENT_VIEW],
  },
  {
    id: "curriculum",
    title: "المستويات الدراسية",
    icon: ChartNoAxesColumnIncreasing,
    url: "/itkan-dashboard/curriculum",
    permissions: [PermissionKeys.ACADEMIC_CURRICULUM_VIEW],
  },
  {
    id: "subjects",
    title: "المنهج التعليمي",
    icon: NotebookPen,
    url: "/itkan-dashboard/subjects",
    permissions: [PermissionKeys.ACADEMIC_EDUCATIONAL_CONTENT_VIEW],
  },
  {
    id: "reports",
    title: "التقارير",
    icon: ListTodo,
    url: "/itkan-dashboard/reports",
    permissions: [
      PermissionKeys.REPORTS_ATTENDANCE_VIEW,
      PermissionKeys.REPORTS_EVALUATIONS_VIEW,
      PermissionKeys.REPORTS_FINANCE_VIEW,
      PermissionKeys.REPORTS_TEACHERS_VIEW,
      PermissionKeys.REPORTS_STAFF_VIEW,
    ],
  },
  {
    id: "question_bank",
    title: "بنك الأسئلة",
    icon: BookOpenCheck,
    url: "/itkan-dashboard/question_bank",
    permissions: [PermissionKeys.ACADEMIC_QUESTION_BANK_VIEW],
  },
  {
    id: "exam_dashboard",
    title: "إدارة الامتحانات",
    icon: Newspaper,
    url: "/itkan-dashboard/exam_dashboard",
    permissions: [PermissionKeys.ACADEMIC_EXAMS_VIEW],
  },
  {
    id: "daily-attendance",
    title: "الحضور",
    icon: BookmarkCheck,
    url: "/itkan-dashboard/daily-attendance",
    permissions: [PermissionKeys.STAFF_ATTENDANCE_CHECKIN],
  },
  {
    id: "attendance-management",
    title: "إدارة الحضور",
    icon: Megaphone,
    url: "/itkan-dashboard/attendance-management",
    permissions: [PermissionKeys.STAFF_ATTENDANCE_CALENDAR_MANAGE],
  },
  {
    id: "attendance-calendars",
    title: "تقويمات الحضور",
    icon: CalendarClock,
    url: "/itkan-dashboard/attendance-calendars",
    permissions: [PermissionKeys.STAFF_ATTENDANCE_CALENDAR_MANAGE],
  },
  {
    id: "work-schedules",
    title: "مواعيد العمل",
    icon: Table,
    url: "/itkan-dashboard/attendance/work-schedules",
    permissions: [PermissionKeys.STAFF_ATTENDANCE_CALENDAR_MANAGE],
  },
  {
    id: "evaluation-cycle",
    title: "دورات التقييم",
    icon: Table,
    url: "/itkan-dashboard/evaluation-cycles",
    permissions: [PermissionKeys.STAFF_EVALUATION_CREATE],
  },
  {
    id: "kpi-templates",
    title: "معايير التقييم",
    icon: Table,
    url: "/itkan-dashboard/kpi-templates",
    permissions: [PermissionKeys.STAFF_EVALUATION_CREATE],
  },
  {
    id: "evaluations",
    title: "التقييم النهائى",
    icon: Table,
    url: "/itkan-dashboard/evaluations",
    permissions: [PermissionKeys.STAFF_EVALUATION_CREATE],
  },
];
