import { PermissionKeys } from "@/constants/permissions";
import {
  BookA,
  BookmarkCheck,
  BookOpenCheck,
  BriefcaseBusiness,
  ListTodo,
  LucideGraduationCap,
  Newspaper,
  UserRound,
  Users,
  Warehouse,
} from "lucide-react";

export const navLinks = [
  {
    id: "branches",
    title: "الفروع",
    icon: Warehouse,
    url: "/itkan-dashboard/branches",
    permissions: [PermissionKeys.SYSTEM_BRANCHES_VIEW],
  },
  {
    id: "roles",
    title: "الادوار الوظيفية",
    icon: BookA,
    url: "/itkan-dashboard/roles",
    permissions: [PermissionKeys.SYSTEM_ROLES_VIEW],
  },
  {
    id: "staff",
    title: "المديرين",
    icon: BriefcaseBusiness,
    url: "/itkan-dashboard/staff",
    permissions: [PermissionKeys.SYSTEM_STAFF_VIEW],
  },
  {
    id: "students",
    title: "الطلاب",
    icon: LucideGraduationCap,
    url: "/itkan-dashboard/students",
    permissions: [PermissionKeys.SYSTEM_STUDENTS_VIEW],
  },
  {
    id: "parents",
    title: "أولياء الأمور",
    icon: Users,
    url: "/itkan-dashboard/parents",
    permission: PermissionKeys.PARENTS_VIEW,
  },
  {
    id: "classes",
    title: "الفصول",
    icon: BookmarkCheck,
    url: "/itkan-dashboard/classes",
    permissions: [PermissionKeys.SYSTEM_TEACHERS_VIEW],
  },
  {
    id: "teachers",
    title: "المعلمين",
    icon: UserRound,
    url: "/itkan-dashboard/teachers",
    permissions: [PermissionKeys.SYSTEM_TEACHERS_VIEW],
  },
  {
    id: "attendance_and_evaluations",
    title: "الحضور و التقييمات",
    icon: BookmarkCheck,
    url: "/itkan-dashboard/attendance-and-evaluations",
    permissions: [PermissionKeys.EVALUATION_STUDENT_VIEW],
  },
  {
    id: "reports",
    title: "التقارير",
    icon: ListTodo,
    url: "/itkan-dashboard/reports",
    permissions: [
      PermissionKeys.REPORTS_ATTENDANCE_VIEW,
      PermissionKeys.REPORTS_EVALUATIONS_VIEW,
      PermissionKeys.REPORTS_FINANCE_VIEW,
      PermissionKeys.REPORTS_TEACHERS_VIEW,
      PermissionKeys.REPORTS_STAFF_VIEW,
    ],
  },
  {
    id: "question_bank",
    title: "بنك الأسئلة",
    icon: BookOpenCheck,
    url: "/itkan-dashboard/question_bank",
    permissions: [PermissionKeys.ACADEMIC_QUESTION_BANK_VIEW],
  },
  {
    id: "exam_dashboard",
    title: "إدارة الامتحانات",
    icon: Newspaper,
    url: "/itkan-dashboard/exam_dashboard",
    permissions: [PermissionKeys.ACADEMIC_EXAMS_VIEW],
  },
];
